Repository assuntaDC/SoundRecorder, pull requests merged in 2020-12, with the labels that each got.

#4 Speech to text
  .idea/caches/build_file_checksums.ser
  .idea/modules/app/SoundRecorder.app.iml
  app/build.gradle
  app/src/main/java/com/danielkim/soundrecorder/CustomAlertDialogForExtractedText.java
  app/src/main/java/com/danielkim/soundrecorder/MySharedPreferences.java
  app/src/main/java/com/danielkim/soundrecorder/RecordingService.java
  app/src/main/java/com/danielkim/soundrecorder/adapters/FileViewerAdapter.java
  app/src/main/java/com/danielkim/soundrecorder/fragments/SettingsFragment.java
  app/src/main/res/layout/dialog_rename_file.xml
  app/src/main/res/layout/fragment_media_playback.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
Labels: enhancement

#5 Aesthetic fixing
  .idea/caches/build_file_checksums.ser
  .idea/modules.xml
  .idea/modules/app/SoundRecorder-app.iml
  .idea/modules/app/app.iml
  .idea/render.experimental.xml
  app/src/main/java/com/danielkim/soundrecorder/CustomAlertDialogForExtractedText.java
  app/src/main/java/com/danielkim/soundrecorder/adapters/FileViewerAdapter.java
  app/src/main/java/com/danielkim/soundrecorder/fragments/SettingsFragment.java
  app/src/main/res/layout/custom_alert_dialog_for_extracted_text.xml
  app/src/main/res/layout/toolbar.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-v21/styles.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/preferences.xml
Labels: bug, enhancement

#6 Pause recording
  .idea/caches/build_file_checksums.ser
  app/src/main/java/com/danielkim/soundrecorder/DBHelper.java
  app/src/main/java/com/danielkim/soundrecorder/RecordingService.java
  app/src/main/java/com/danielkim/soundrecorder/adapters/FileViewerAdapter.java
  app/src/main/java/com/danielkim/soundrecorder/fragments/RecordFragment.java
Labels: enhancement

#8 Unit test
  .idea/SoundRecorder.iml
  .idea/caches/build_file_checksums.ser
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/app/SoundRecorder.app.iml
  .idea/modules/app/app.iml
  app/checkstyle.xml
  app/src/main/java/com/danielkim/soundrecorder/DBHelper.java
  app/src/main/java/com/danielkim/soundrecorder/mockclasses/MockRecordingService.java
  app/src/test/java/com/assuntadc/soundrecorder/unittest/MockRecordingServiceTest.java
  build.gradle
  documentation/SoundRecorder Class Diagram.png
  gradle/wrapper/gradle-wrapper.properties
Labels: documentation, enhancement
